on:
  workflow_call:
jobs:
  deploy-ec2:
    name: "🚀deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Download image tag artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tag

      - name: Load Docker image tag
        id: get-docker-image-tag
        run: echo "image-tag=$(cat image-tag.txt)" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        env:
          APP_NAME: "mock_application"
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.MOCK_SERVER_ECR_REPO_NAME }}
          IMAGE_TAG:  ${{ steps.get-docker-image-tag.outputs.image-tag }}
        with:
          host: ${{ secrets.MOCK_SERVER_EC2_HOST }}
          username: ${{ secrets.MOCK_SERVER_EC2_USER_NAME }}
          key: ${{ secrets.MOCK_SERVER_SECRET_KEY }}
          script_stop: true
          script: |
            echo "ECR Registry: ${{ env.ECR_REGISTRY }}"
            echo "ECR Repository: ${{ env.ECR_REPOSITORY }}"
            echo "Image Tag: ${{ env.IMAGE_TAG }}"
            
            aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}
            echo "Using image tag: $IMAGE_TAG"
            docker ps -a
            docker pull ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
            docker run -d -p 8082:8082 --name $APP_NAME $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
